### ISSUE TITLE
1.1.5 Additional research on functional requirements (FR) and non-functional requirements(NFR)

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#14]
Task title ID
#14

What is this task about? 
This task is about revisiting the FR and NFR after revamping the UCD. Also, updating the existing FR & NFR according to the client's requirement after exchanging information via email.

What are the goals of the task? 
Goals of this task is to have clear view on the FR & NFR that is needed for our airline scheduling system to run efficiently and smoothly without any hiccups. Having a clear view enables the team to work in the same direction without wasting resources pursing unrelated topics.

Success or completion criteria. 
Completion criteria would be covering all the bases of requirement stated by the client, project description from LMS as well as the team's envisioned requirements for the scheduling system.

Allocated time
1 week

Start and end date for the issue/task
18/02/23 - 22/09/23

Who is the owner? 
Reness

Task Status. 
Completed

What is the priority of this task?
Medium Priority

**Comment by Thrith10** [comment]
i. Describe the work done in detail
After having communicated with the client via email, I've updated the FR & NFR accordingly and also revisited the project description to get a better understanding of the overall requirements stated. After the discussion with the team, added additional FRs such as adding new FRs to the IT Administrator's role of add, edit, view and delete

ii. Has this work been committed to the repo?
Yes can refer to it below 

iii. How does the work affect success of completion criteria?
With the updated FR & NFR, our team was able to get a better idea of the problem we are trying to solve. It ensured us to work towards the same goal following the stated requirements.

iv. Start and end date of the work done
19/09/23 - 22/09/23

**Functional Requirements**

FR1: Airline manager access landing page
The airline manager shall be able to access the manager landing page.

FR2: Airline manager access job allocation page
The airline manager shall be able to access the job allocation page.

FR3: Airline manager view pilot workload
The airline manager shall be able to view pilot workload immediately on the manager landing page, up to one month earlier.

FR4: Airline manager allocate jobs to pilot
The airline manager shall be able to allocate jobs based on rank to pilots every week on the job allocation page. 

FR5: Airline manager view pilot’s assigned workload
The airline manager shall be able to view workload that has already been assigned to pilots on the job allocation page.

FR6: Airline manager view pilot’s preference
The airline manager shall be able to view the pilot’s preferred job on the job allocation page.

FR7: Airline manager view pilot’s location
The airline manager shall be able to view where the pilot will be located on a particular date on the job allocation page.

FR8: Airline manager view pilot’s availabilities
The airline manager shall be able to view the pilots’ availability for the week on the job allocation page.

FR9: Airline Manager view pilot’s workload hours
The airline manager shall be able to view the top three pilots with the lowest workload, as well as pilots highlighted with over 40 hours of jobs allocated on the manager landing page.

FR10: Airline manager view aircraft availability
The airline manager shall be able to view aircraft availability on the job allocation page.

FR11: Airline manager allocate aircraft to route
The airline manager shall be able to allocate short haul or long haul assignment depending on the route on the job allocation page.

FR12: Airline manager view standby pool of pilots 
The airline manager shall be able to view pilots that being put on standby due to flight being 
cancelled or additional pilots without any job assignment

FR13: Pilot access staff landing page
The pilot shall be able to access the staff landing page.

FR14: Pilot view weekly job assignment
The pilot shall be able to view weekly job assignments on staff landing page

FR15: Pilot view overall workload
The pilot shall be able to view the overall monthly workload on the staff landing page.

FR16: Pilot add availability
The pilot shall be be able to add availability up to 5 weeks ahead of time on the staff landing page

FR17: Pilot edit availability
The pilot shall be able to edit availability up to 5 weeks ahead of time on the staff landing page.

FR18: Pilot indicate job preference
The pilot shall be able to indicate their preference of their jobs up to 5 weeks ahead of time on the staff landing page.

FR19: Pilot reject job assignments
The pilot shall be able to reject job assignments on the staff landing page. 

FR20: System show warning to pilot
The system shall be able to issue a warning to the pilots that wish to reject the jobs assigned to them and will advise them to discuss the action with their manager before proceeding with rejection.

FR21: IT Administrator add employee
The IT administrator shall be able to add new employees such as airline managers or pilots into the system.

FR22: IT Administrator view employee
The IT administrator shall be able to view employees such as airline managers or pilots in the system.

FR23: IT Administrator delete employee
The IT administrator shall be able to delete specific employees from the system.

FR24: IT Administrator update employee
The IT administrator shall be able to update specific employee’s information in the system.

**Non-Functional Requirements**

NFR1: System usability
Pilots, airline managers, and IT administrators shall be able to learn all the functions of the system in under 5 hours. After this training, errors made by experienced users shall not exceed 3 per hour of system use.

NFR2: System use on platforms
The web-based application shall be able to support the five most used browsers: Google Chrome, Safari, Edge, Samsung Internet, and Mozilla Firefox.

NFR3: System performance
The system shall respond to user clicks in under 0.05 seconds.

NFR4: System reliability
The system shall not experience downtime of more than 1 hour per week(168 hours) of operation.
