### ISSUE TITLE
1.3.4 System architecture diagram

### ISSUE THREAD

**Issue by LilZBJ** [Mhidayah19/INF2001-P5_1#19]
1. Task title ID
#19

2. What is this task about? Describe in detail
This task is about creating a system architecture that is high level while also being structured representation of the scheduling system's design. 

3. What are the goals of the task? Describe in detail
Goal of this task is to list all the third party and software that will be involved in the development phase of the scheduling system in order for the development to be as efficient as possible while being productive.

4. Success or completion criteria. Describe in detail
Completion criteria would mean covering all the software and third party that will be involved while building the scheduling system from scratch.

5. Allocated time
5 days

6. Start and end date for the issue/task
18/09/23 - 22/09-23

7. Who is the owner? 
Reness

9. Task Status.
Completed

10. What is the priority of this task?
Low priority

**Comment by Thrith10** [comment]
i. Describe the work done in detail
After researching about the software and third party that will be requirement for the scheduling system, I begun to design the system architecture diagram that can clearly reflect our goals. Team recommended some of the software such as the preferred database because working with familiar software can make the work easier and also to execute within the time frame without much issues.


ii. Has this work been committed to the repo?
Yes refer the image below

iii. How does the work affect success of completion criteria?
Having a whole picture of system architecture diagram enables team to be able to visualize the software and third party our scheduling system will be using and give some time to get familiarize with some of the new software involved.

iv. Start and end date of the work done
19/09/23 - 22/09/23

![Image](https://github.com/Mhidayah19/INF2001-P5_1/assets/116250188/eb6bb076-67e5-45ef-8ddf-02a8cb8bee27)
