### ISSUE TITLE
3.5 Project Prototype & Wireframes

### ISSUE THREAD

**Issue by Mhidayah19** [Mhidayah19/INF2001-P5_1#41]
Task title ID: #41

What is this task about?
Create a prototype of our project

What are the goals of the task?
The goal of this task is to describe the concepts, flow, and user interaction of the application using figma.

Success or completion criteria.
The completion criteria is when we have created figma pages that covers all of the uses cases and functional requirements

Allocated time
18 days.

Start and end date for the issue/task
Start date: 19 November 2023 End date: 25 November 2023

Who is the owner? Owner is the person in charge of the task and should be created and maintained by the owner.
Owner: Sim Xin Rong @LilZBJ 

Task Status. Usually under "To-Do".
Status: To-Do

What is the priority of this task?
High priority

**Comment by Thrith10** [comment]
i. Describe the work done in detail
Created project wireframes based on the use case descriptions using Figma. Covered every use case descriptions with relevant wireframes of airline scheduling system.

ii. Has this work been committed to the repo?
No because its a link to the Figma : https://www.figma.com/file/uAPCDKCAFeOPWyYnT3A63I/INF2001_Team01?type=design&node-id=0%3A1&mode=design&t=HP0vjYK482K16Ki5-1

iii. How does the work affect success of completion criteria?
We have a clearer vision of how the airline scheduling system user interface is going to look like before starting the actual development work. Client will have the opportunity to fine tune the user interfaces and developer can make changes accordingly.

iv. Start and end date of the work done
6 Nov 2023 to 25 Nov 2023
